//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeDim.StackBuilder.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreeDim.StackBuilder.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Analysis {
            get {
                object obj = ResourceManager.GetObject("Analysis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnalysisBundle {
            get {
                object obj = ResourceManager.GetObject("AnalysisBundle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Box {
            get {
                object obj = ResourceManager.GetObject("Box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bundle {
            get {
                object obj = ResourceManager.GetObject("Bundle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CaseAnalysis {
            get {
                object obj = ResourceManager.GetObject("CaseAnalysis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileNew {
            get {
                object obj = ResourceManager.GetObject("FileNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileOpen {
            get {
                object obj = ResourceManager.GetObject("FileOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileSave {
            get {
                object obj = ResourceManager.GetObject("FileSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileSaveAll {
            get {
                object obj = ResourceManager.GetObject("FileSaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string ID_ABOUT {
            get {
                return ResourceManager.GetString("ID_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new analysis....
        /// </summary>
        internal static string ID_ADDNEWANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new box....
        /// </summary>
        internal static string ID_ADDNEWBOX {
            get {
                return ResourceManager.GetString("ID_ADDNEWBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new bundle....
        /// </summary>
        internal static string ID_ADDNEWBUNDLE {
            get {
                return ResourceManager.GetString("ID_ADDNEWBUNDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new bundle analysis....
        /// </summary>
        internal static string ID_ADDNEWBUNDLEANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWBUNDLEANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new interlayer....
        /// </summary>
        internal static string ID_ADDNEWINTERLAYER {
            get {
                return ResourceManager.GetString("ID_ADDNEWINTERLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new pallet....
        /// </summary>
        internal static string ID_ADDNEWPALLET {
            get {
                return ResourceManager.GetString("ID_ADDNEWPALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new truck....
        /// </summary>
        internal static string ID_ADDNEWTRUCK {
            get {
                return ResourceManager.GetString("ID_ADDNEWTRUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new truck analysis....
        /// </summary>
        internal static string ID_ADDNEWTRUCKANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWTRUCKANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ID_CLOSE {
            get {
                return ResourceManager.GetString("ID_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        internal static string ID_DELETE {
            get {
                return ResourceManager.GetString("ID_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has some depending analyses.\nIf you proceed with the modifications, analyses will be recomputed and any selected solutions removed.\nContinue?.
        /// </summary>
        internal static string ID_DEPENDINGANALYSES {
            get {
                return ResourceManager.GetString("ID_DEPENDINGANALYSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}....
        /// </summary>
        internal static string ID_EDIT {
            get {
                return ResourceManager.GetString("ID_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} could not be found.
        /// </summary>
        internal static string ID_FILENOTFOUND {
            get {
                return ResourceManager.GetString("ID_FILENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate report for {0}.
        /// </summary>
        internal static string ID_GENERATEREPORT {
            get {
                return ResourceManager.GetString("ID_GENERATEREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyses.
        /// </summary>
        internal static string ID_NODE_ANALYSES {
            get {
                return ResourceManager.GetString("ID_NODE_ANALYSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes.
        /// </summary>
        internal static string ID_NODE_BOXES {
            get {
                return ResourceManager.GetString("ID_NODE_BOXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundles.
        /// </summary>
        internal static string ID_NODE_BUNDLES {
            get {
                return ResourceManager.GetString("ID_NODE_BUNDLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlayers.
        /// </summary>
        internal static string ID_NODE_INTERLAYERS {
            get {
                return ResourceManager.GetString("ID_NODE_INTERLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallets.
        /// </summary>
        internal static string ID_NODE_PALLETS {
            get {
                return ResourceManager.GetString("ID_NODE_PALLETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks.
        /// </summary>
        internal static string ID_NODE_TRUCKS {
            get {
                return ResourceManager.GetString("ID_NODE_TRUCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file {0}?.
        /// </summary>
        internal static string ID_SAVEMODIFIEDFILE {
            get {
                return ResourceManager.GetString("ID_SAVEMODIFIEDFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version : {0}.
        /// </summary>
        internal static string ID_VERSION {
            get {
                return ResourceManager.GetString("ID_VERSION", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Interlayer {
            get {
                object obj = ResourceManager.GetObject("Interlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pallet {
            get {
                object obj = ResourceManager.GetObject("Pallet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PatternCollumn {
            get {
                object obj = ResourceManager.GetObject("PatternCollumn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PatternInterlocked {
            get {
                object obj = ResourceManager.GetObject("PatternInterlocked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon treeDim {
            get {
                object obj = ResourceManager.GetObject("treeDim", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Truck {
            get {
                object obj = ResourceManager.GetObject("Truck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View_1 {
            get {
                object obj = ResourceManager.GetObject("View_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View_2 {
            get {
                object obj = ResourceManager.GetObject("View_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View_3 {
            get {
                object obj = ResourceManager.GetObject("View_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View_4 {
            get {
                object obj = ResourceManager.GetObject("View_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View_Top {
            get {
                object obj = ResourceManager.GetObject("View_Top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View0 {
            get {
                object obj = ResourceManager.GetObject("View0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View180 {
            get {
                object obj = ResourceManager.GetObject("View180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View270 {
            get {
                object obj = ResourceManager.GetObject("View270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View90 {
            get {
                object obj = ResourceManager.GetObject("View90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
