//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeDim.StackBuilder.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreeDim.StackBuilder.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Analysis {
            get {
                object obj = ResourceManager.GetObject("Analysis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnalysisBundle {
            get {
                object obj = ResourceManager.GetObject("AnalysisBundle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AnalysisStackingStrength {
            get {
                object obj = ResourceManager.GetObject("AnalysisStackingStrength", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Box {
            get {
                object obj = ResourceManager.GetObject("Box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bundle {
            get {
                object obj = ResourceManager.GetObject("Bundle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Case {
            get {
                object obj = ResourceManager.GetObject("Case", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CaseAnalysis {
            get {
                object obj = ResourceManager.GetObject("CaseAnalysis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Database {
            get {
                object obj = ResourceManager.GetObject("Database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileNew {
            get {
                object obj = ResourceManager.GetObject("FileNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileOpen {
            get {
                object obj = ResourceManager.GetObject("FileOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileSave {
            get {
                object obj = ResourceManager.GetObject("FileSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileSaveAll {
            get {
                object obj = ResourceManager.GetObject("FileSaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1.
        /// </summary>
        internal static string ID_A1 {
            get {
                return ResourceManager.GetString("ID_A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A2.
        /// </summary>
        internal static string ID_A2 {
            get {
                return ResourceManager.GetString("ID_A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A3.
        /// </summary>
        internal static string ID_A3 {
            get {
                return ResourceManager.GetString("ID_A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string ID_ABOUT {
            get {
                return ResourceManager.GetString("ID_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new analysis....
        /// </summary>
        internal static string ID_ADDNEWANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new box....
        /// </summary>
        internal static string ID_ADDNEWBOX {
            get {
                return ResourceManager.GetString("ID_ADDNEWBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new bundle....
        /// </summary>
        internal static string ID_ADDNEWBUNDLE {
            get {
                return ResourceManager.GetString("ID_ADDNEWBUNDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new bundle analysis....
        /// </summary>
        internal static string ID_ADDNEWBUNDLEANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWBUNDLEANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new case....
        /// </summary>
        internal static string ID_ADDNEWCASE {
            get {
                return ResourceManager.GetString("ID_ADDNEWCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new case analysis....
        /// </summary>
        internal static string ID_ADDNEWCASEANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWCASEANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new ECT analysis....
        /// </summary>
        internal static string ID_ADDNEWECTANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWECTANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new interlayer....
        /// </summary>
        internal static string ID_ADDNEWINTERLAYER {
            get {
                return ResourceManager.GetString("ID_ADDNEWINTERLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new pallet....
        /// </summary>
        internal static string ID_ADDNEWPALLET {
            get {
                return ResourceManager.GetString("ID_ADDNEWPALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new truck....
        /// </summary>
        internal static string ID_ADDNEWTRUCK {
            get {
                return ResourceManager.GetString("ID_ADDNEWTRUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new truck analysis....
        /// </summary>
        internal static string ID_ADDNEWTRUCKANALYSIS {
            get {
                return ResourceManager.GetString("ID_ADDNEWTRUCKANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow aligned and/or alternate layers.
        /// </summary>
        internal static string ID_ALLOWALIGNEDORALTERNATELAYERS {
            get {
                return ResourceManager.GetString("ID_ALLOWALIGNEDORALTERNATELAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string ID_AREA {
            get {
                return ResourceManager.GetString("ID_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box/Case count.
        /// </summary>
        internal static string ID_BOXCASECOUNT {
            get {
                return ResourceManager.GetString("ID_BOXCASECOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        internal static string ID_CASE {
            get {
                return ResourceManager.GetString("ID_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create case analysis as the constraint set appears to be invalid..
        /// </summary>
        internal static string ID_CASEANALYSIS_INVALIDCONSTRAINTSET {
            get {
                return ResourceManager.GetString("ID_CASEANALYSIS_INVALIDCONSTRAINTSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case count.
        /// </summary>
        internal static string ID_CASECOUNT {
            get {
                return ResourceManager.GetString("ID_CASECOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case dimensions.
        /// </summary>
        internal static string ID_CASEDIMENSIONS {
            get {
                return ResourceManager.GetString("ID_CASEDIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case inside dimensions.
        /// </summary>
        internal static string ID_CASEINSIDEDIMENSIONS {
            get {
                return ResourceManager.GetString("ID_CASEINSIDEDIMENSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case/pallet.
        /// </summary>
        internal static string ID_CASEPERPALLET {
            get {
                return ResourceManager.GetString("ID_CASEPERPALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases/Layer.
        /// </summary>
        internal static string ID_CASESLAYER {
            get {
                return ResourceManager.GetString("ID_CASESLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases/Pallet.
        /// </summary>
        internal static string ID_CASESPALLET {
            get {
                return ResourceManager.GetString("ID_CASESPALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Google Chrome browser needs to be installed to visualize collada/webGL animations..
        /// </summary>
        internal static string ID_CHROMEISNOTINSTALLED {
            get {
                return ResourceManager.GetString("ID_CHROMEISNOTINSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ID_CLOSE {
            get {
                return ResourceManager.GetString("ID_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet solution database is empty.
        ///Closing form....
        /// </summary>
        internal static string ID_DATABASEEMPTY {
            get {
                return ResourceManager.GetString("ID_DATABASEEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define at least one stacking pattern.
        /// </summary>
        internal static string ID_DEFINEATLEASTONEPATTERN {
            get {
                return ResourceManager.GetString("ID_DEFINEATLEASTONEPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define at least one vertical axis.
        /// </summary>
        internal static string ID_DEFINEATLEASTONEVERTICALAXIS {
            get {
                return ResourceManager.GetString("ID_DEFINEATLEASTONEVERTICALAXIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        internal static string ID_DELETE {
            get {
                return ResourceManager.GetString("ID_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has some depending analyses.
        ///If you proceed with the modifications, analyses will be recomputed and any selected solutions removed.
        ///Continue?.
        /// </summary>
        internal static string ID_DEPENDINGANALYSES {
            get {
                return ResourceManager.GetString("ID_DEPENDINGANALYSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect.
        /// </summary>
        internal static string ID_DESELECT {
            get {
                return ResourceManager.GetString("ID_DESELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECT.
        /// </summary>
        internal static string ID_ECT {
            get {
                return ResourceManager.GetString("ID_ECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge Crush Test Analysis.
        /// </summary>
        internal static string ID_EDGECRUSHTEST {
            get {
                return ResourceManager.GetString("ID_EDGECRUSHTEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}....
        /// </summary>
        internal static string ID_EDIT {
            get {
                return ResourceManager.GetString("ID_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency (%).
        /// </summary>
        internal static string ID_EFFICIENCY {
            get {
                return ResourceManager.GetString("ID_EFFICIENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency (%).
        /// </summary>
        internal static string ID_EFFICIENCYPERCENTAGE {
            get {
                return ResourceManager.GetString("ID_EFFICIENCYPERCENTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description field is empty.
        /// </summary>
        internal static string ID_FIELDDESCRIPTIONEMPTY {
            get {
                return ResourceManager.GetString("ID_FIELDDESCRIPTIONEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name field is empty.
        /// </summary>
        internal static string ID_FIELDNAMEEMPTY {
            get {
                return ResourceManager.GetString("ID_FIELDNAMEEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} could not be found.
        /// </summary>
        internal static string ID_FILENOTFOUND {
            get {
                return ResourceManager.GetString("ID_FILENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate 3D animation file for {0}.
        /// </summary>
        internal static string ID_GENERATECOLLADA {
            get {
                return ResourceManager.GetString("ID_GENERATECOLLADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a report for {0}.
        /// </summary>
        internal static string ID_GENERATEREPORT {
            get {
                return ResourceManager.GetString("ID_GENERATEREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate HTML report for {0}.
        /// </summary>
        internal static string ID_GENERATEREPORTHTML {
            get {
                return ResourceManager.GetString("ID_GENERATEREPORTHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Word report for {0}.
        /// </summary>
        internal static string ID_GENERATEREPORTMSWORD {
            get {
                return ResourceManager.GetString("ID_GENERATEREPORTMSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string ID_HEIGHT {
            get {
                return ResourceManager.GetString("ID_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string ID_INDEX {
            get {
                return ResourceManager.GetString("ID_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum volume is insufficient to pack {0} {1} ..
        /// </summary>
        internal static string ID_INSUFFICIENTVOLUME {
            get {
                return ResourceManager.GetString("ID_INSUFFICIENTVOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside height ({0}) ought to be lower than height ({1}).
        /// </summary>
        internal static string ID_INVALIDINSIDEHEIGHT {
            get {
                return ResourceManager.GetString("ID_INVALIDINSIDEHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside length ({0}) ought to be lower than length ({1}).
        /// </summary>
        internal static string ID_INVALIDINSIDELENGTH {
            get {
                return ResourceManager.GetString("ID_INVALIDINSIDELENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside width ({0}) ought to be lower than width ({1}).
        /// </summary>
        internal static string ID_INVALIDINSIDEWIDTH {
            get {
                return ResourceManager.GetString("ID_INVALIDINSIDEWIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name ({0}) is invalid.
        /// </summary>
        internal static string ID_INVALIDNAME {
            get {
                return ResourceManager.GetString("ID_INVALIDNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer pattern.
        /// </summary>
        internal static string ID_LAYERPATTERN {
            get {
                return ResourceManager.GetString("ID_LAYERPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer pattern(s).
        /// </summary>
        internal static string ID_LAYERPATTERNS {
            get {
                return ResourceManager.GetString("ID_LAYERPATTERNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string ID_LAYERS {
            get {
                return ResourceManager.GetString("ID_LAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string ID_LAYOUT {
            get {
                return ResourceManager.GetString("ID_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string ID_LENGTH {
            get {
                return ResourceManager.GetString("ID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load height (mm).
        /// </summary>
        internal static string ID_LOADHEIGHT {
            get {
                return ResourceManager.GetString("ID_LOADHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load (kg).
        /// </summary>
        internal static string ID_LOADWEIGHT {
            get {
                return ResourceManager.GetString("ID_LOADWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistency:Maximum {0} is lower than minimum {1}..
        /// </summary>
        internal static string ID_MAXLOWERTHANMIN {
            get {
                return ResourceManager.GetString("ID_MAXLOWERTHANMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ID_NAME {
            get {
                return ResourceManager.GetString("ID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyses.
        /// </summary>
        internal static string ID_NODE_ANALYSES {
            get {
                return ResourceManager.GetString("ID_NODE_ANALYSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes.
        /// </summary>
        internal static string ID_NODE_BOXES {
            get {
                return ResourceManager.GetString("ID_NODE_BOXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundles.
        /// </summary>
        internal static string ID_NODE_BUNDLES {
            get {
                return ResourceManager.GetString("ID_NODE_BUNDLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases.
        /// </summary>
        internal static string ID_NODE_CASES {
            get {
                return ResourceManager.GetString("ID_NODE_CASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlayers.
        /// </summary>
        internal static string ID_NODE_INTERLAYERS {
            get {
                return ResourceManager.GetString("ID_NODE_INTERLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallets.
        /// </summary>
        internal static string ID_NODE_PALLETS {
            get {
                return ResourceManager.GetString("ID_NODE_PALLETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks.
        /// </summary>
        internal static string ID_NODE_TRUCKS {
            get {
                return ResourceManager.GetString("ID_NODE_TRUCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string ID_ORIENTATION {
            get {
                return ResourceManager.GetString("ID_ORIENTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit pallet {0}....
        /// </summary>
        internal static string ID_PALLETCAPTIONEDIT {
            get {
                return ResourceManager.GetString("ID_PALLETCAPTIONEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet count.
        /// </summary>
        internal static string ID_PALLETCOUNT {
            get {
                return ResourceManager.GetString("ID_PALLETCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet height (mm).
        /// </summary>
        internal static string ID_PALLETHEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit reached.
        /// </summary>
        internal static string ID_PALLETLIMIT {
            get {
                return ResourceManager.GetString("ID_PALLETLIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string ID_PALLETMAXHEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETMAXHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string ID_PALLETMAXNUMBER {
            get {
                return ResourceManager.GetString("ID_PALLETMAXNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string ID_PALLETMAXWEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETMAXWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet weight (kg).
        /// </summary>
        internal static string ID_PALLETWEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ID_READY {
            get {
                return ResourceManager.GetString("ID_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file {0}?.
        /// </summary>
        internal static string ID_SAVEMODIFIEDFILE {
            get {
                return ResourceManager.GetString("ID_SAVEMODIFIEDFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string ID_SELECT {
            get {
                return ResourceManager.GetString("ID_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string ID_SELECTED {
            get {
                return ResourceManager.GetString("ID_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to database.
        /// </summary>
        internal static string ID_SENDTODATABASE {
            get {
                return ResourceManager.GetString("ID_SENDTODATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect solution {0}.
        /// </summary>
        internal static string ID_UNSELECTSOLUTION {
            get {
                return ResourceManager.GetString("ID_UNSELECTSOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define at least one stop stacking criterion.
        /// </summary>
        internal static string ID_USEATLEASTONESTOPSTACKINGCRITERION {
            get {
                return ResourceManager.GetString("ID_USEATLEASTONESTOPSTACKINGCRITERION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version : {0}.
        /// </summary>
        internal static string ID_VERSION {
            get {
                return ResourceManager.GetString("ID_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (kg).
        /// </summary>
        internal static string ID_WEIGHT {
            get {
                return ResourceManager.GetString("ID_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string ID_WIDTH {
            get {
                return ResourceManager.GetString("ID_WIDTH", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Image {
            get {
                object obj = ResourceManager.GetObject("Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Interlayer {
            get {
                object obj = ResourceManager.GetObject("Interlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OptimalCase {
            get {
                object obj = ResourceManager.GetObject("OptimalCase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pallet {
            get {
                object obj = ResourceManager.GetObject("Pallet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon treeDim {
            get {
                object obj = ResourceManager.GetObject("treeDim", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Truck {
            get {
                object obj = ResourceManager.GetObject("Truck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View_1 {
            get {
                object obj = ResourceManager.GetObject("View_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View_2 {
            get {
                object obj = ResourceManager.GetObject("View_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View_3 {
            get {
                object obj = ResourceManager.GetObject("View_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View_4 {
            get {
                object obj = ResourceManager.GetObject("View_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View_Top {
            get {
                object obj = ResourceManager.GetObject("View_Top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View0 {
            get {
                object obj = ResourceManager.GetObject("View0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View180 {
            get {
                object obj = ResourceManager.GetObject("View180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View270 {
            get {
                object obj = ResourceManager.GetObject("View270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View90 {
            get {
                object obj = ResourceManager.GetObject("View90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
