//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeDim.StackBuilder.Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::TreeDim.StackBuilder.Desktop.WindowSettings FormMainPosition {
            get {
                return ((global::TreeDim.StackBuilder.Desktop.WindowSettings)(this["FormMainPosition"]));
            }
            set {
                this["FormMainPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::TreeDim.StackBuilder.Desktop.WindowSettings FormNewDocumentPosition {
            get {
                return ((global::TreeDim.StackBuilder.Desktop.WindowSettings)(this["FormNewDocumentPosition"]));
            }
            set {
                this["FormNewDocumentPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::TreeDim.StackBuilder.Desktop.WindowSettings FormNewBoxPosition {
            get {
                return ((global::TreeDim.StackBuilder.Desktop.WindowSettings)(this["FormNewBoxPosition"]));
            }
            set {
                this["FormNewBoxPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::TreeDim.StackBuilder.Desktop.WindowSettings FormNewPalletPosition {
            get {
                return ((global::TreeDim.StackBuilder.Desktop.WindowSettings)(this["FormNewPalletPosition"]));
            }
            set {
                this["FormNewPalletPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::TreeDim.StackBuilder.Desktop.WindowSettings FormNewInterlayerPosition {
            get {
                return ((global::TreeDim.StackBuilder.Desktop.WindowSettings)(this["FormNewInterlayerPosition"]));
            }
            set {
                this["FormNewInterlayerPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::TreeDim.StackBuilder.Desktop.WindowSettings FormNewBundlePosition {
            get {
                return ((global::TreeDim.StackBuilder.Desktop.WindowSettings)(this["FormNewBundlePosition"]));
            }
            set {
                this["FormNewBundlePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DocumentAuthor {
            get {
                return ((string)(this["DocumentAuthor"]));
            }
            set {
                this["DocumentAuthor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowAlignedLayer {
            get {
                return ((bool)(this["AllowAlignedLayer"]));
            }
            set {
                this["AllowAlignedLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowAlternateLayer {
            get {
                return ((bool)(this["AllowAlternateLayer"]));
            }
            set {
                this["AllowAlternateLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AllowedPatterns {
            get {
                return ((string)(this["AllowedPatterns"]));
            }
            set {
                this["AllowedPatterns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::TreeDim.StackBuilder.Desktop.WindowSettings FormNewAnalysisPosition {
            get {
                return ((global::TreeDim.StackBuilder.Desktop.WindowSettings)(this["FormNewAnalysisPosition"]));
            }
            set {
                this["FormNewAnalysisPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowVerticalX {
            get {
                return ((bool)(this["AllowVerticalX"]));
            }
            set {
                this["AllowVerticalX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowVerticalY {
            get {
                return ((bool)(this["AllowVerticalY"]));
            }
            set {
                this["AllowVerticalY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowVerticalZ {
            get {
                return ((bool)(this["AllowVerticalZ"]));
            }
            set {
                this["AllowVerticalZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PalletOverhangLength {
            get {
                return ((int)(this["PalletOverhangLength"]));
            }
            set {
                this["PalletOverhangLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PalletOverhangWidth {
            get {
                return ((int)(this["PalletOverhangWidth"]));
            }
            set {
                this["PalletOverhangWidth"] = value;
            }
        }
    }
}
