//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeDim.StackBuilder.GUIExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreeDim.StackBuilder.GUIExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1.
        /// </summary>
        internal static string ID_A1 {
            get {
                return ResourceManager.GetString("ID_A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A2.
        /// </summary>
        internal static string ID_A2 {
            get {
                return ResourceManager.GetString("ID_A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A3.
        /// </summary>
        internal static string ID_A3 {
            get {
                return ResourceManager.GetString("ID_A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacking case {0} on pallet {1} .
        /// </summary>
        internal static string ID_ANALYSISDESCRIPTION {
            get {
                return ResourceManager.GetString("ID_ANALYSISDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_on_{1}.
        /// </summary>
        internal static string ID_ANALYSISNAME {
            get {
                return ResourceManager.GetString("ID_ANALYSISNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string ID_AREA {
            get {
                return ResourceManager.GetString("ID_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case count.
        /// </summary>
        internal static string ID_CASECOUNT {
            get {
                return ResourceManager.GetString("ID_CASECOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases/Layer.
        /// </summary>
        internal static string ID_CASESLAYER {
            get {
                return ResourceManager.GetString("ID_CASESLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases/Pallet.
        /// </summary>
        internal static string ID_CASESPALLET {
            get {
                return ResourceManager.GetString("ID_CASESPALLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string ID_HEIGHT {
            get {
                return ResourceManager.GetString("ID_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string ID_INDEX {
            get {
                return ResourceManager.GetString("ID_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal pallet height ({0} {1}) ought to exceed {1} {2}.
        /// </summary>
        internal static string ID_INSUFFICIENTPALLETHEIGHT {
            get {
                return ResourceManager.GetString("ID_INSUFFICIENTPALLETHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum volume is insufficient to pack {0} {1} ..
        /// </summary>
        internal static string ID_INSUFFICIENTVOLUME {
            get {
                return ResourceManager.GetString("ID_INSUFFICIENTVOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer pattern.
        /// </summary>
        internal static string ID_LAYERPATTERN {
            get {
                return ResourceManager.GetString("ID_LAYERPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string ID_LAYERS {
            get {
                return ResourceManager.GetString("ID_LAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string ID_LENGTH {
            get {
                return ResourceManager.GetString("ID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistency: Maximum {0} is lower than minimum {1}..
        /// </summary>
        internal static string ID_MAXLOWERTHANMIN {
            get {
                return ResourceManager.GetString("ID_MAXLOWERTHANMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet analysis generated by case optimisation for box {0} and pallet {1}.
        /// </summary>
        internal static string ID_OPTANALYSISDESCRIPTION {
            get {
                return ResourceManager.GetString("ID_OPTANALYSISDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptimAnalysis{0}_{1}*{2}*{3}_{4}{5}.
        /// </summary>
        internal static string ID_OPTANALYSISNAME {
            get {
                return ResourceManager.GetString("ID_OPTANALYSISNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case generated by case optimization for box {0} and pallet {1}.
        /// </summary>
        internal static string ID_OPTCASEDESCRIPTION {
            get {
                return ResourceManager.GetString("ID_OPTCASEDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimal palletisation for box {0}.
        /// </summary>
        internal static string ID_OPTDOCUMENTDESCRIPTION {
            get {
                return ResourceManager.GetString("ID_OPTDOCUMENTDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet height.
        /// </summary>
        internal static string ID_PALLETHEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit reached.
        /// </summary>
        internal static string ID_PALLETLIMIT {
            get {
                return ResourceManager.GetString("ID_PALLETLIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string ID_PALLETMAXHEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETMAXHEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string ID_PALLETMAXNUMBER {
            get {
                return ResourceManager.GetString("ID_PALLETMAXNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string ID_PALLETMAXWEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETMAXWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet weight ({0}).
        /// </summary>
        internal static string ID_PALLETWEIGHT {
            get {
                return ResourceManager.GetString("ID_PALLETWEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ID_READY {
            get {
                return ResourceManager.GetString("ID_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume efficiency (%).
        /// </summary>
        internal static string ID_VOLUMEEFFICIENCY {
            get {
                return ResourceManager.GetString("ID_VOLUMEEFFICIENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string ID_WIDTH {
            get {
                return ResourceManager.GetString("ID_WIDTH", resourceCulture);
            }
        }
    }
}
