//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeDim.EdgeCrushTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreeDim.EdgeCrushTest.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 day.
        /// </summary>
        internal static string STORAGEDURATION_0DAY {
            get {
                return ResourceManager.GetString("STORAGEDURATION_0DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-2 monthes.
        /// </summary>
        internal static string STORAGEDURATION_1_2MONTHES {
            get {
                return ResourceManager.GetString("STORAGEDURATION_1_2MONTHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-3 days.
        /// </summary>
        internal static string STORAGEDURATION_1_3DAYS {
            get {
                return ResourceManager.GetString("STORAGEDURATION_1_3DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11-30 days.
        /// </summary>
        internal static string STORAGEDURATION_11_30DAYS {
            get {
                return ResourceManager.GetString("STORAGEDURATION_11_30DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-3 monthes.
        /// </summary>
        internal static string STORAGEDURATION_2_3MONTHES {
            get {
                return ResourceManager.GetString("STORAGEDURATION_2_3MONTHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-4 monthes.
        /// </summary>
        internal static string STORAGEDURATION_3_4MONTHES {
            get {
                return ResourceManager.GetString("STORAGEDURATION_3_4MONTHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-10 days.
        /// </summary>
        internal static string STORAGEDURATION_4_10DAYS {
            get {
                return ResourceManager.GetString("STORAGEDURATION_4_10DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than 4 monthes.
        /// </summary>
        internal static string STORAGEDURATION_4_MONTHES {
            get {
                return ResourceManager.GetString("STORAGEDURATION_4_MONTHES", resourceCulture);
            }
        }
    }
}
