//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeDim.EdgeCrushTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreeDim.EdgeCrushTest.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American case.
        /// </summary>
        internal static string CASETYPE_AMERICANCASE {
            get {
                return ResourceManager.GetString("CASETYPE_AMERICANCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown cardboard id: {0}.
        /// </summary>
        internal static string EXCEPTION_INVALIDCARDBOARDID {
            get {
                return ResourceManager.GetString("EXCEPTION_INVALIDCARDBOARDID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown case type: {0}.
        /// </summary>
        internal static string EXCEPTION_INVALIDCASETYPE {
            get {
                return ResourceManager.GetString("EXCEPTION_INVALIDCASETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid formula type (Should be either CLASSIC or IMPROVED).
        /// </summary>
        internal static string EXCEPTION_INVALIDFORMULA {
            get {
                return ResourceManager.GetString("EXCEPTION_INVALIDFORMULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string MCKEEFORMULA_CLASSIC {
            get {
                return ResourceManager.GetString("MCKEEFORMULA_CLASSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved.
        /// </summary>
        internal static string MCKEEFORMULA_IMPROVED {
            get {
                return ResourceManager.GetString("MCKEEFORMULA_IMPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardboard quality database file  could not be found..
        /// </summary>
        internal static string MESSAGE_CARDBOARDQUALITYDBNOTFOUND {
            get {
                return ResourceManager.GetString("MESSAGE_CARDBOARDQUALITYDBNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        internal static string PRINTEDSURFACE_COMPLEX {
            get {
                return ResourceManager.GetString("PRINTEDSURFACE_COMPLEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covered.
        /// </summary>
        internal static string PRINTEDSURFACE_COVERED {
            get {
                return ResourceManager.GetString("PRINTEDSURFACE_COVERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed.
        /// </summary>
        internal static string PRINTEDSURFACE_DISTRIBUTED {
            get {
                return ResourceManager.GetString("PRINTEDSURFACE_DISTRIBUTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string PRINTEDSURFACE_SIMPLE {
            get {
                return ResourceManager.GetString("PRINTEDSURFACE_SIMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string PRINTEDSURFACE_UNKNOWN {
            get {
                return ResourceManager.GetString("PRINTEDSURFACE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 day.
        /// </summary>
        internal static string STORAGEDURATION_0DAY {
            get {
                return ResourceManager.GetString("STORAGEDURATION_0DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-3 days.
        /// </summary>
        internal static string STORAGEDURATION_1_3DAYS {
            get {
                return ResourceManager.GetString("STORAGEDURATION_1_3DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-3 monthes.
        /// </summary>
        internal static string STORAGEDURATION_1_3MONTHES {
            get {
                return ResourceManager.GetString("STORAGEDURATION_1_3MONTHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11-30 days.
        /// </summary>
        internal static string STORAGEDURATION_11_30DAYS {
            get {
                return ResourceManager.GetString("STORAGEDURATION_11_30DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-4 monthes.
        /// </summary>
        internal static string STORAGEDURATION_3_4MONTHES {
            get {
                return ResourceManager.GetString("STORAGEDURATION_3_4MONTHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-10 days.
        /// </summary>
        internal static string STORAGEDURATION_4_10DAYS {
            get {
                return ResourceManager.GetString("STORAGEDURATION_4_10DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than 4 monthes.
        /// </summary>
        internal static string STORAGEDURATION_4_MONTHES {
            get {
                return ResourceManager.GetString("STORAGEDURATION_4_MONTHES", resourceCulture);
            }
        }
    }
}
