<?xml version="1.0" ?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:template match="report">
    <html>
      <head>
        <title>
          <xsl:value-of select="name"/> report
        </title>
        <style type="text/css">
          .style1
          {
          width: 100%;
          }
          .style2
          {
          width: 233px;background-color: #CCCCCC;
          }
          .style3
          {
          }
        </style>
      </head>
      <body>
        <h4 style="text-align:center">
          Report generated by treeDiM StackBuilder
        </h4>
        <table border="0">
          <tr>
            <td>
              <b>Document:</b>
            </td>
            <td>
              <xsl:value-of select="name"/>
            </td>
          </tr>
          <tr>
            <td>
              <b>Description:</b>
            </td>
            <td>
              <xsl:value-of select="description"/>
            </td>
          </tr>
          <tr>
            <td>
              <b>Date:</b>
            </td>
            <td>
              <xsl:value-of select="dateOfCreation"/>
            </td>
            <td>
              <b>Author:</b>
            </td>
            <td>
              <xsl:value-of select="author"/>
            </td>
          </tr>
        </table>
        <xsl:apply-templates select="palletAnalysis"/>
      </body>
    </html>
  </xsl:template>
  <xsl:template match="palletAnalysis">
    <h2 style="font-family:arial;color:red;">Pallet analysis</h2>
    <xsl:apply-templates select="case"/>
    <xsl:apply-templates select="box"/>
    <xsl:apply-templates select="bundle"/>
    <xsl:apply-templates select="interlayer"/>
    <xsl:apply-templates select="pallet"/>
    <xsl:apply-templates select="constraintSet"/>
    <xsl:apply-templates select="palletSolution"/>
  </xsl:template>

  <!-- #### CASE ####-->
  <xsl:template match="case">
    <h3 style="font-family:arial;color:blue;">Case</h3>
    <table class="style1" cellpadding="3">
      <tr>
        <td class="style2" colspan="1">
          <b>Name:</b>
        </td>
        <td class="style3" colspan="2">
          <xsl:value-of select="name"/>
        </td>
      </tr>
      <tr>
        <td class="style2" colspan="1">
          <b>Description:</b>
        </td>
        <td class="style3" colspan="2">
          <xsl:value-of select="description"/>
        </td>
      </tr>
      <tr>
        <td  class="style2" colspan="1">
          <b>Length (mm):</b>
        </td>
        <td class="style3" colspan="1">
          <xsl:value-of select="length"/>
        </td>
        <td rowspan="5">
          <xsl:apply-templates select="view_case_iso"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <b>Width (mm):</b>
        </td>
        <td class="style3" colspan="1">
          <xsl:value-of select="width"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <b>Height (mm):</b>
        </td>
        <td class="style3" colspan="1">
          <xsl:value-of select="height"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <b>Weight (kg):</b>
        </td>
        <td class="style3" colspan="1">
          <xsl:value-of select="weight"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <b>Admissible load on top (kg):</b>
        </td>
        <td class="style3" colspan="1">
          <xsl:value-of select="admissibleLoad"/>
        </td>
      </tr>
    </table>
  </xsl:template>
  <!-- #### PALLET ####-->
  <xsl:template match="pallet">
    <h3 style="font-family:arial;color:blue;">Pallet</h3>
    <table class="style1" cellpadding="3">
      <tr>
        <td  class="style2" colspan="1">
          <b>Name:</b>
        </td>
        <td class="style3" colspan="2">
          <xsl:value-of select="name"/>
        </td>
      </tr>
      <tr>
        <td  class="style2" colspan="1">
          <b>Description:</b>
        </td>
        <td class="style3" colspan="2">
          <xsl:value-of select="description"/>
        </td>
      </tr>
      <tr>
        <td  class="style2" colspan="1">
          <b>Length (mm):</b>
        </td>
        <td class="style3" colspan="1">
          <xsl:value-of select="length"/>
        </td>
        <td rowspan="5">
          <xsl:apply-templates select="view_pallet_iso"/>
        </td>
      </tr>
      <tr>
        <td  class="style2" colspan="1">
          <b>Width (mm):</b>
        </td>
        <td class="style3" colspan="1">
          <xsl:value-of select="width"/>
        </td>
      </tr>
      <tr>
        <td  class="style2" colspan="1">
          <b>Height (mm):</b>
        </td>
        <td class="style3" colspan="1">
          <xsl:value-of select="height"/>
        </td>
      </tr>
      <tr>
        <td  class="style2" colspan="1">
          <b>Weight (kg):</b>
        </td>
        <td class="style3" colspan="1">
          <xsl:value-of select="weight"/>
        </td>
      </tr>
      <tr>
        <td  class="style2" colspan="1">
          <b>Admissible load weight (kg):</b>
        </td>
        <td class="style3" colspan="1">
          <xsl:value-of select="admissibleLoad"/>
        </td>
      </tr>
    </table>
  </xsl:template>
  <!--BOX-->
  <xsl:template match="box">
    <h3 style="font-family:arial;color:blue;">Box</h3>
    <table class="style1">
      <tr>
        <td class="style2">
          <b>Name:</b>
        </td>
      </tr>
    </table>
  </xsl:template>
  <!--#### INTERLAYER ####-->
  <xsl:template match="interlayer">
    <h3 style="font-family:arial;color:blue;">Interlayer</h3>
    <table class="style1">
      <tr>
        <td  class="style2">
          <b>Name:</b>
        </td>
        <td class="style3" colspan="2">
          <xsl:value-of select="name"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <b>Description:</b>
        </td>
        <td class="style3" colspan="2">
          <xsl:value-of select="description"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <strong>Length (mm):</strong>
        </td>
        <td class="style3">
          <xsl:value-of select="length"/>
        </td>
        <td rowspan="4">
          <xsl:apply-templates select="view_interlayer_iso"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <strong>Width (mm):</strong>
        </td>
        <td class="style3">
          <xsl:value-of select="width"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <strong>Thickness (mm):</strong>
        </td>
        <td class="style3">
          <xsl:value-of select="thickness"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <b>Weight (kg):</b>
        </td>
        <td class="style3">
          <xsl:value-of select="weight"/>
        </td>
      </tr>
    </table>
  </xsl:template>
  <!--#### BUNDLE ####-->
  <xsl:template match="bundle">
    <h3 style="font-family:arial;color:blue;">Bundle</h3>
    <table class="style1">
      <tr>
        <td  class="style2">
          <b>Name:</b>
        </td>
        <td colspan="2">
          <xsl:value-of select="name"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <b>Description:</b>
        </td>
        <td colspan="2">
          <xsl:value-of select="description"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <strong>Length (mm):</strong>
        </td>
        <td class="style3">
          <xsl:value-of select="length"/>
        </td>
        <td rowspan="6">
          <xsl:apply-templates select="view_bundle_iso"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <strong>Width (mm):</strong>
        </td>
        <td class="style3">
          <xsl:value-of select="width"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <strong>Number of flats:</strong>
        </td>
        <td class="style3">
          <xsl:value-of select="numberOfFlats"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <b>Unit thickness (mm):</b>
        </td>
        <td class="style3">
          <xsl:value-of select="unitThickness"/>
        </td>
      </tr>
      <tr>
        <td  class="style2">
          <b>Unit weight (kg):</b>
        </td>
        <td class="style3">
          <xsl:value-of select="unitWeight"/>
        </td>
      </tr>
      <tr>
        <td class="style3">
          <b>Total thickness (mm)</b>
        </td>
        <td class="style3">
          <xsl:value-of select="totalThickness"/>
        </td>
      </tr>
      <tr>
        <td class="style3">
          <b>Total weight (mm)</b>
        </td>
        <td class="style3">
          <xsl:value-of select="totalWeight"/>
        </td>
      </tr>
    </table>
  </xsl:template>
  <!--#### CONSTRAINT SET ####-->
  <xsl:template match="constraintSet">
    <h3 style="font-family:arial;color:blue;">Constraint set</h3>
    <table class="style1">
      <tr>
        <td class="style2">Overhang (mm)</td>
        <td class="style3">X</td>
        <td class="style3">
          <xsl:value-of select="overhangX"/>
        </td>
        <td class="style3">Y</td>
        <td class="style3">
          <xsl:value-of select="overhangY"/>
        </td>
      </tr>
      <xsl:apply-templates select="maximumPalletWeightGroup">
      </xsl:apply-templates>
      <xsl:apply-templates select="maximumPalletHeightGroup">
      </xsl:apply-templates>
      <xsl:apply-templates select="maximumNumberOfItemsGroup">
      </xsl:apply-templates>
      <xsl:apply-templates select="admissibleLoadOnTopGroup">
      </xsl:apply-templates>
      <tr>
        <td class="style2">Allowed patterns:</td>
        <td class="style3" colspan="3">
          <xsl:value-of select="allowedPatterns"/>
        </td>
      </tr>
      <tr>
        <td class="style2">Allowed ortho axes:</td>
        <td class="style3" colspan="3">
          <xsl:value-of select="allowedOrthoAxis"/>
        </td>
      </tr>
      <tr>
        <td class="style2">Allow aligned layers</td>
        <td class="style3" colspan="3">
          <xsl:value-of select="allowAlignedLayers"/>
        </td>
      </tr>
      <tr>
        <td class="style2">Allow alternate layers</td>
        <td class="style3" colspan="3">
          <xsl:value-of select="allowAlternateLayers"/>
        </td>
      </tr>
      <xsl:apply-templates select="interlayerPeriodGroup">
      </xsl:apply-templates>
    </table>
  </xsl:template>
  <!--#### PALLET SOLUTION ####-->
  <xsl:template match="palletSolution">
    <h3 style="font-family:arial;color:blue;">Selected solution</h3>
    <table class="style1">
      <tr>
        <td class="style2">Title</td>
        <td class="style3" colspan="3">
          <xsl:value-of select="title"/>
        </td>
      </tr>
      <tr>
        <td class="style2">Number of cases</td>
        <td class="style3" colspan="3">
          <xsl:value-of select="caseCount"/>
        </td>
      </tr>
      <tr>
        <td class="style2">Number of interlayers</td>
        <td class="style3" colspan="3">
          <xsl:value-of select="interlayerCount"/>
        </td>
      </tr>
      <tr>
        <td class="style2">Pallet weight (kg)</td>
        <td class="style3" colspan="3">
          <xsl:value-of select="palletWeight"/>
        </td>
      </tr>
      <tr>
        <td class="style2">Pallet height (mm)</td>
        <td class="style3" colspan="3">
          <xsl:value-of select="palletHeight"/>
        </td>
      </tr>
      <tr>
        <td class="style2">Efficiency (%)</td>
        <td class="style3" colspan="3">
          <xsl:value-of select="efficiency"/>
        </td>
      </tr>
      <tr>
        <td>
          <xsl:apply-templates select="view_palletsolution_front"/>
        </td>
        <td>
          <xsl:apply-templates select="view_palletsolution_left"/>
        </td>
        <td>
          <xsl:apply-templates select="view_palletsolution_right"/>
        </td>
        <td>
          <xsl:apply-templates select="view_palletsolution_back"/>
        </td>
      </tr>
      <tr>
        <td colspan="4">
          <xsl:apply-templates select="view_palletsolution_iso"/>
        </td>
      </tr>
    </table>
    <h3 style="font-family:arial;color:blue;">Layers</h3>
    <table class="style1">
      <tr>
        <td class="style2">
          <xsl:value-of select="layerId"/>
        </td>
        <td class="style3">
          <xsl:apply-templates select="layerImage"/>
        </td>
      </tr>
    </table>
  </xsl:template>
  <!--CASE-->
  <xsl:template match="view_case_iso">
    <img src="images\view_case_iso.gif" width="150" height="150"></img>
  </xsl:template>
  <!--PALLET-->
  <xsl:template match="view_pallet_iso">
    <img src="images\view_pallet_iso.gif" width="150" height="150"></img>
  </xsl:template>
  <!--INTERLAYER-->
  <xsl:template match="view_interlayer_iso">
    <img src="images\view_interlayer_iso.gif" width="150" height="150"></img>
  </xsl:template>
  <!--BUNDLE-->
  <xsl:template match="view_bundle_iso">
    <img src="images\view_interlayer_iso.gif" width="150" height="150"></img>
  </xsl:template>
  <!--PALLET SOLUTION-->
  <xsl:template match="view_palletsolution_front">
    <img src="images\view_palletsolution_front.gif" width="150" height="150"></img>
  </xsl:template>
  <xsl:template match="view_palletsolution_left">
    <img src="images\view_palletsolution_left.gif" width="150" height="150"></img>
  </xsl:template>
  <xsl:template match="view_palletsolution_right">
    <img src="images\view_palletsolution_right.gif" width="150" height="150"></img>
  </xsl:template>
  <xsl:template match="view_palletsolution_back">
    <img src="images\view_palletsolution_back.gif" width="150" height="150"></img>
  </xsl:template>
  <xsl:template match="view_palletsolution_iso">
    <img src="images\view_palletsolution_iso.gif" width="450" height="450"></img>
  </xsl:template>
  <!--STOP STACKING CONDITIONS-->
  <xsl:template match="maximumPalletWeightGroup">
    <tr>
      <td class="style2">Maximum pallet weight (kg):</td>
      <td class="style3" colspan="3">
        <xsl:value-of select="maximumPalletWeight"/>
      </td>
    </tr>
  </xsl:template>
  <xsl:template match="maximumPalletHeightGroup">
    <tr>
      <td class="style2">Maximum pallet height (kg):</td>
      <td class="style3" colspan="3">
        <xsl:value-of select="maximumPalletHeight"/>
      </td>
    </tr>
  </xsl:template>
  <xsl:template match="maximumNumberOfItemsGroup">
    <tr>
      <td class="style2">Maximum number of items</td>
      <td class="style3" colspan="3">
        <xsl:value-of select="maximumNumberOfItems"/>
      </td>
    </tr>
  </xsl:template>
  <xsl:template match="admissibleLoadOnTopGroup">
    <tr>
      <td class="style2">Maximum load on top group (kg)</td>
      <td class="style3" colspan="3">
        <xsl:value-of select="admissibleLoadOnTop"/>
      </td>
    </tr>
  </xsl:template>
  <!--INTERLAYER PERIOD-->
  <xsl:template match="interlayerPeriodGroup">
    <tr>
      <td class="style2">Interlayer period</td>
      <td class="style3" colspan="3">
        <xsl:value-of select="interlayerPeriod"/>
      </td>
    </tr>
  </xsl:template>
  <!--LAYER-->
  <xsl:template match="layerImage">
    <img src="images\layerImage1.gif" width="150" height="150"></img>
  </xsl:template>
</xsl:stylesheet>
